### ISSUE TITLE
[BUG] Cap sprites (Cybersun Intern and Frontiersman) break once they are taken off

### ISSUE THREAD

**Issue by generalthrax** [shiptest-ss13/Shiptest#3579] opened 2024-10-17 02:57 UTC
## Round ID:
2769

## Testmerges:

Recurring for a while, absolutely not any of these

## Reproduction:

- put on a frontie or Cybersun intern hat
- take it off
- sprite goes invisible

**Comment by Orchidthederg** [comment] 2024-10-17 21:50
Can't reproduce on local branch. Is it happening with any specific species?

**Comment by rye-rice** [comment] 2024-10-17 22:02
Fixed by #3581

**Closed as completed by rye-rice** 2024-10-17 22:02 UTC
Labels: Bug
