### ISSUE TITLE
[BUG] Welding goggles work in a Kepori's beak

### ISSUE THREAD

**Issue by Leon9621** [shiptest-ss13/Shiptest#3657] opened 2024-10-27 08:42 UTC
## Round ID:

2814

## Testmerges:

Not sure it's relevant, it was the last round on saturday uptime 10/26/2024

## Reproduction:
Play kepori

Put welding goggles in your beak

Activate welding goggles

???

Welding protection
![f1ot4e4](https://github.com/user-attachments/assets/5041b6fb-f51d-4a80-b62e-fd0ef98548cb)
![7mAMN5X](https://github.com/user-attachments/assets/25412d0d-ad64-4c44-91d1-cb6b0ffe92d1)

**Comment by randy10122** [comment] 2024-11-15 01:57
duplicate of #1748 (and #2519)

**Closed as completed** 2024-11-27 18:51 UTC
Labels: Bug
