### ISSUE TITLE
[BUG] Wearing things casually don't work for most clothing 

### ISSUE THREAD

**Issue by TypeVar** [shiptest-ss13/Shiptest#1186] opened 2022-06-08 21:53 UTC
## Round ID:
All of them

## Testmerges:
I don't think this is the result of a test merge for this has been an issue for a long time.

## Reproduction:
Wearing most jumpsuits casually don't work EXCEPT for the utility jumpsuit, but only when worn on a feminine character for some reason. The sprite does change somewhat (like 2 pixels change) when wearing something casually, but it's not working as intended I don't think.
Normal:
![image](https://user-images.githubusercontent.com/100787466/172723453-37bec516-0c58-42f1-8380-054cdde10108.png)
Normal with utility jumpsuit on feminine mob:
![image](https://user-images.githubusercontent.com/100787466/172723617-9d5c3b7e-6a7e-4296-96a7-5a71361711bc.png)

Casual:
![image](https://user-images.githubusercontent.com/100787466/172723532-57e63a9e-5c3c-4d39-ad4c-51609a61341a.png)
Casual with utility jumpsuit on feminine mob:
![image](https://user-images.githubusercontent.com/100787466/172723647-9e784d3a-f349-4e58-8e25-98fe483a84df.png)

**Comment by triplezeta** [comment] 2022-06-08 21:54
duplicate of https://github.com/shiptest-ss13/Shiptest/issues/1076

**Closed as completed by triplezeta** 2022-06-08 21:54 UTC
Labels: Bug, Duplicate
