### ISSUE TITLE
[BUG] Social anxiety trait checks for radio me's even though it shouldnt

### ISSUE THREAD

**Issue by Hlscientist** [shiptest-ss13/Shiptest#2893] opened 2024-04-12 19:21 UTC
## Round ID:
 2329

## Testmerges:
 N/A, bug should not be caused by any active TMs

## Reproduction:
1 - Have social anxiety trait
2 - have social anxiety
3 - attempt to radio me ( ; beeps*)
4 - cry as the moment is ruined as you have social anxiety and the radio me does not go through

**Comment by FalloutFalcon** [comment] 2024-09-11 00:16
I cant reproduce this. I think its related to eye contact which is annoying to replicate on local host by myself

**Comment by FalloutFalcon** [comment] 2024-09-14 18:18
fixed in #3222

**Closed as completed by FalloutFalcon** 2024-09-14 18:18 UTC
Labels: Bug
